classifiers:
  - name: random_forest_learner
    params:
      - n_estimators: [ 100, 300, 500 ]
        max_depth: [ null, 10, 20 ]
        min_samples_split: [ 2, 5, 10 ]
        min_samples_leaf: [ 1, 2, 4 ]
        representation_type: ["woe", "sklearn_tfidf"]

  - name: extra_tree_learner
    params:
      - n_estimators: [ 100, 300, 500 ]
        max_depth: [ null, 10, 20 ]
        min_samples_split: [ 2, 5, 10 ]
        min_samples_leaf: [ 1, 2, 4 ]
        representation_type: ["woe", "sklearn_tfidf"]

  - name: ada_boost_learner
    params:
      - n_estimators: [ 50, 100, 200 ]
        learning_rate: [ 0.01, 0.1, 1 ]
        representation_type: ["woe", "sklearn_tfidf"]

  - name: gradient_boost_learner
    params:
      - n_estimators: [ 100, 200, 300 ]
        learning_rate: [ 0.01, 0.1, 0.2 ]
        max_depth: [ 3, 5, 7 ]
        representation_type: ["woe", "sklearn_tfidf"]

  - name: xgboost_learner
    params:
      - n_estimators: [ 100, 200, 300 ]
        learning_rate: [ 0.01, 0.1, 0.2 ]
        max_depth: [ 3, 6, 9 ]
        subsample: [ 0.8, 1 ]
        colsample_bytree: [ 0.8, 1 ]
        representation_type: ["woe", "sklearn_tfidf"]

  - name: lightgbm_learner
    params:
      - n_estimators: [ 100, 200, 300 ]
        learning_rate: [ 0.01, 0.1, 0.2 ]
        max_depth: [ -1, 10, 20 ] # -1 for no limit
        num_leaves: [ 31, 62, 127 ]
        subsample: [ 0.8, 1 ]
        colsample_bytree: [ 0.8, 1 ]
        representation_type: ["woe", "sklearn_tfidf"]

  - name: catboost_learner
    params:
      - iterations: [ 100, 300, 500 ]
        learning_rate: [ 0.01, 0.1, 0.2 ]
        depth: [ 4, 6, 10 ]
        l2_leaf_reg: [ 1, 3, 5 ]
        representation_type: ["woe", "sklearn_tfidf"]
